
name: Check License Lines
on:
  push:
jobs:
  check-license-lines:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v19
    - name: Check License for changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          npm install -g @kt3k/license-checker
          echo $file
          license_checker
        done
