# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2019-2021 Xilinx, Inc. All rights reserved.

name: License Checking
on:     
  push:

jobs:
  license_check:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout XRT on pull request
      uses: actions/checkout@v2
      
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3.3.0
      with:
        node-version: 16.x
        
    - name: Install Dependencies
      run: |
        npx @saumyag-xilinx/XRT/license-checker
        license_checker        
