
name: Check License Lines
on:
  push:
jobs:
  check-license-lines:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@master
    - name: Check License Lines
      run: |
        URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
        FILES=$(curl -s -X GET -G $URL)
        for f in ${FILES[*]}; do
          echo "checking $f ..."
          #git submodule file is coming as null here, so skip further checks for this type of files
          if [ $f == null ]; then
            continue;
